version: '3'

services:
  database:
    image: mysql:8
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symshop
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

  mailer:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
